
remote_theme: "jekyll/minima@1e8a445"
theme: minima
minima:
  nav_pages:
    -index.md
    -README.md
        
        
title: Welcome to The Office 
description: Philosophy either, how long you might have to study for!
author: uk
email: udaykr119@gmail.com
site_nav: true
order: 1




