theme: minima
title: Welcome to The Office 
description: Philosophy either, how long you might have to study for!
author: uk
site_nav: true
order: 1



minima:
  nav_pages:
    - ./README.md
    - ./index.md
